### ISSUE TITLE
알림 클릭 시 Promise detail 화면으로 못들어가는 버그

### ISSUE THREAD

**Issue by dogeby** [boostcampwm-2022/android03-Promise#100]
- [ ] promiseInfo를 nullable로 수정

**Comment by hoho-97** [comment]
#### 원인
##### UI
- ViewModel에서 데이터를 읽는 작업을 수행하지만 UI에는 초기값이 반영됨
##### 데이터 호출
- 업데이트된 PromiseInfo를 통해 데이터를 Firebase에서 호출하고 있음 -> Coroutine으로 동작하기 때문에 PromiseInfo의 초기값으로 호출하기 때문에 나는 오류 (PromiseInfo 업데이트를 기다리는 작업 필요)

-> 위 문제들을 해결하기 위해 state도입과 flow 코드 수정이 필요해 보임
https://developer.android.com/kotlin/flow/stateflow-and-sharedflow#livedata

**Comment by dogeby** [comment]
- [x] promiseInfo를 nullable로 수정 (임시 조치)

제대로 고칠려면 상당한 작업을 필요로할거같기에 임시 조치함
